name: 'ECS services for Image'
description: 'Get all ECS task definitions that use a given image family'
inputs:
  imageFamily:
    description: 'Image family'
    required: true
  awsAccessKeyId:
    description: 'AWS Access Key ID'
    required: true
  awsSecretAccessKey:
    description: 'AWS Secret Access Key'
    required: true
outputs:
  services:
    description: 'Array of simplified ECS service objects'
runs:
  using: 'node12'
  main: 'index.js'
